on:
  push:
    branchs: main  
  schedule:
    # every UTC 17:00 -> CST (China) 1:00
    - cron: '0 17 * * *'
name: mirror Github repos to Gitee
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: get repository list exclude private and fork
      id: repo
      uses: yi-Xu-0100/repo-list-generator@v1.0.1
    - name: mirror Github repos to Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/Yang-Xijie
        dst: gitee/yang-xijie
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true
        account_type: user
        debug: true
